# Generated by Django 5.2.17 on 2026-09-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('overture_id', models.CharField(help_text='Overture division_area GERS id.', max_length=64, unique=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
