/**
 * Minimal typed fetch wrapper for the backend API.
 *
 * Phase 1 only needs the health probe. From Phase 4 on, response types come from
 * `schema.gen.ts` (generated by `make types` from the OpenAPI schema) and this module grows
 * a typed client around them. Until then the only hand-written shape is `HealthStatus`,
 * validated at runtime with a guard rather than trusted via a cast.
 */

export const API_BASE = '/api/v1';

/** Response of `GET /api/v1/health`. Replaced by the generated schema type in Phase 4. */
export interface HealthStatus {
  status: 'ok';
  warehouse: boolean;
}

function isHealthStatus(value: unknown): value is HealthStatus {
  if (typeof value !== 'object' || value === null) return false;
  const record = value as Record<string, unknown>;
  return record.status === 'ok' && typeof record.warehouse === 'boolean';
}

/**
 * Fetch the backend health probe.
 *
 * @throws Error when the request fails or the payload does not match the expected shape.
 */
export async function fetchHealth(signal?: AbortSignal): Promise<HealthStatus> {
  // Absolute URL: Node's fetch (used by Vitest) rejects relative paths that the browser accepts.
  const url = new URL(`${API_BASE}/health`, window.location.origin);
  const response = await fetch(url, { signal });
  if (!response.ok) {
    throw new Error(`Health request failed with HTTP ${String(response.status)}`);
  }
  const payload: unknown = await response.json();
  if (!isHealthStatus(payload)) {
    throw new Error('Health response did not match the expected shape');
  }
  return payload;
}
