/**
 * Typed fetch wrapper for the backend API.
 *
 * Every response type comes from `schema.gen.ts` (regenerated by `make types` from the
 * OpenAPI schema); nothing here mirrors a payload by hand. Errors are RFC 7807 problem
 * details, surfaced as `ApiError` so the UI can distinguish "warehouse not built" (503) and
 * "invalid polygon" (422) from a network failure.
 */

import type { District, Health, KpiRequestRequest, KpiResponse, Problem } from './schema.gen';

export const API_BASE = '/api/v1';

/** An error response the backend described as RFC 7807 problem details. */
export class ApiError extends Error {
  readonly problem: Problem;

  constructor(problem: Problem) {
    super(problem.detail);
    this.name = 'ApiError';
    this.problem = problem;
  }

  /** HTTP status of the problem (422 invalid area, 503 warehouse not built, ...). */
  get status(): number {
    return this.problem.status;
  }
}

function isProblem(value: unknown): value is Problem {
  if (typeof value !== 'object' || value === null) return false;
  const record = value as Record<string, unknown>;
  return typeof record.title === 'string' && typeof record.status === 'number';
}

async function request<T>(path: string, init: RequestInit): Promise<T> {
  // Absolute URL: Node's fetch (used by Vitest) rejects relative paths that the browser accepts.
  const url = new URL(`${API_BASE}${path}`, window.location.origin);
  const response = await fetch(url, init);
  if (!response.ok) {
    const body: unknown = await response.json().catch(() => null);
    if (isProblem(body)) throw new ApiError(body);
    throw new Error(`${path} failed with HTTP ${String(response.status)}`);
  }
  return (await response.json()) as T;
}

/** `GET /api/v1/health`. */
export function fetchHealth(signal?: AbortSignal): Promise<Health> {
  return request<Health>('/health', { signal });
}

/** `POST /api/v1/kpis`: every KPI for a district, a bbox or a drawn polygon. */
export function fetchKpis(body: KpiRequestRequest, signal?: AbortSignal): Promise<KpiResponse> {
  return request<KpiResponse>('/kpis', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
    signal,
  });
}

/** `GET /api/v1/districts`: outlines and bounds to draw and fit the map on load. */
export function fetchDistricts(signal?: AbortSignal): Promise<District[]> {
  return request<District[]>('/districts', { signal });
}
