/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List districts (outline geometry from the warehouse). */
        get: operations["districts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return ``{"status": "ok", "warehouse": <bool>}``. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Compute every KPI for the given area. Exactly one of district, bbox or polygon. An area with no data (e.g. drawn outside the district) is a 200 with sample_size 0 and value null on every KPI, not an error. */
        post: operations["kpis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The area the numbers describe. */
        Area: {
            /**
             * Format: double
             * @description Share of the area that lies inside the loaded district, i.e. that has data. 1 for the district itself; 0 for a polygon drawn elsewhere.
             */
            district_overlap_share: number;
            /** Format: double */
            km2: number;
            name: string;
            source: components["schemas"]["AreaSource"];
        };
        /**
         * @description * `district` - DISTRICT
         *     * `bbox` - BBOX
         *     * `drawn` - DRAWN
         * @enum {string}
         */
        AreaSource: "district" | "bbox" | "drawn";
        /** @description value <= max; the last band has max = null. */
        Band: {
            label: string;
            /** Format: double */
            max: number | null;
        };
        /** @description One slice of a KPI (a chart bar, a map category). Keys match layer feature categories. */
        BreakdownItem: {
            key: string;
            label: string;
            /** Format: double */
            value: number;
        };
        /** @description A figure needed to read the value, e.g. the share of streets with a mapped limit. */
        ContextItem: {
            key: string;
            label: string;
            unit: string;
            /** Format: double */
            value: number | null;
        };
        /**
         * @description * `carriageway_length_m` - CARRIAGEWAY_LENGTH_M
         *     * `network_length_m` - NETWORK_LENGTH_M
         *     * `building_count` - BUILDING_COUNT
         * @enum {string}
         */
        Denominator: "carriageway_length_m" | "network_length_m" | "building_count";
        /** @description A district the API knows: what the map draws and fits to on load. */
        District: {
            /** @description [xmin, ymin, xmax, ymax] in EPSG:4326. */
            bbox: number[];
            /** @description GeoJSON geometry, EPSG:4326, coordinates rounded to 5 decimals (~1 m). The frontend narrows this to @types/geojson in one adapter (frontend/src/api/geojson.ts). */
            geometry: {
                coordinates: unknown[];
                /** @enum {string} */
                type: "Point" | "LineString" | "Polygon" | "MultiPoint" | "MultiLineString" | "MultiPolygon";
            };
            /** Format: double */
            km2: number;
            name: string;
            slug: string;
        };
        /** @description A GeoJSON Feature; ``id`` is the Overture GERS id. */
        Feature: {
            /** @description GeoJSON geometry, EPSG:4326, coordinates rounded to 5 decimals (~1 m). The frontend narrows this to @types/geojson in one adapter (frontend/src/api/geojson.ts). */
            geometry: {
                coordinates: unknown[];
                /** @enum {string} */
                type: "Point" | "LineString" | "Polygon" | "MultiPoint" | "MultiLineString" | "MultiPolygon";
            };
            id: string;
            properties: components["schemas"]["FeatureProperties"];
            type: components["schemas"]["FeatureTypeEnum"];
        };
        /** @description A GeoJSON FeatureCollection in EPSG:4326. */
        FeatureCollection: {
            features: components["schemas"]["Feature"][];
            type: components["schemas"]["FeatureCollectionTypeEnum"];
        };
        /**
         * @description * `FeatureCollection` - FeatureCollection
         * @enum {string}
         */
        FeatureCollectionTypeEnum: "FeatureCollection";
        /** @description Exactly what the frontend reads: the category to filter on and the contribution value. */
        FeatureProperties: {
            /**
             * Format: double
             * @description Green spaces.
             */
            area_ha?: number;
            /** @description Matches a breakdown/legend key of the KPI. */
            category: string;
            /**
             * Format: double
             * @description Distance to the nearest target (building centroids).
             */
            distance_m?: number;
            /**
             * Format: double
             * @description Clipped length (streets).
             */
            length_m?: number;
            /** @description Street or park name, when mapped. */
            name?: string;
        };
        /**
         * @description * `Feature` - Feature
         * @enum {string}
         */
        FeatureTypeEnum: "Feature";
        /** @description Liveness plus whether the DuckDB warehouse file is present. */
        Health: {
            status: components["schemas"]["StatusEnum"];
            /** @description True when data/warehouse.duckdb exists, i.e. `make load-data` has run. */
            warehouse: boolean;
        };
        /** @description One KPI: its number for this area and the metadata to read it honestly. */
        Kpi: {
            band: string | null;
            bands: components["schemas"]["Band"][];
            breakdown?: components["schemas"]["BreakdownItem"][];
            /** @description Present when the KPI deliberately has no breakdown, saying why. */
            breakdown_note?: string;
            context: components["schemas"]["ContextItem"][];
            definition: string;
            denominator: components["schemas"]["Denominator"];
            key: string;
            label: string;
            /** @description Orders bands; never colours them. */
            lower_is_better: boolean;
            not_claim: string;
            /** @description Features behind the number; 0 is the empty state. */
            sample_size: number;
            source: components["schemas"]["Source"];
            unit: string;
            /**
             * Format: double
             * @description null when sample_size is 0.
             */
            value: number | null;
        };
        /** @description Exactly one of ``district``, ``bbox`` or ``polygon``. */
        KpiRequestRequest: {
            /** @description [xmin, ymin, xmax, ymax] in EPSG:4326 (lon, lat). */
            bbox?: number[];
            /** @description District slug, e.g. eixample. */
            district?: string;
            polygon?: components["schemas"]["PolygonRequest"];
        };
        /** @description POST /api/v1/kpis response. */
        KpiResponse: {
            area: components["schemas"]["Area"];
            insights: string[];
            kpis: components["schemas"]["Kpi"][];
            layers: components["schemas"]["Layers"];
            legend: components["schemas"]["Legend"];
            meta: components["schemas"]["Meta"];
        };
        /** @description A map layer explaining one KPI. */
        Layer: {
            readonly data: components["schemas"]["FeatureCollection"];
            id: string;
            kpi_key: string;
        };
        /** @description Layer container (room for raster layers later without a breaking change). */
        Layers: {
            vectors: components["schemas"]["Layer"][];
        };
        /** @description Every map category with its colour. */
        Legend: {
            items: components["schemas"]["LegendItem"][];
            readonly type: components["schemas"]["LegendTypeEnum"];
        };
        /** @description A category of one KPI's map layer and its colour. */
        LegendItem: {
            /** @description #rrggbb */
            color: string;
            key: string;
            kpi_key: string;
            label: string;
        };
        /** @enum {string} */
        LegendTypeEnum: "categorical";
        /** @description Provenance and timing. */
        Meta: {
            cached: boolean;
            /** Format: double */
            computed_ms: number;
            overture_release: string;
            /** @description Per KPI and per layer (layer:<id>). */
            timings_ms: {
                [key: string]: number;
            };
            /** @description Short hash of the warehouse build. */
            warehouse_build: string;
        };
        /** @description A GeoJSON Polygon in EPSG:4326: rings of [lon, lat] positions. */
        PolygonRequest: {
            coordinates: number[][][];
            type: components["schemas"]["PolygonTypeEnum"];
        };
        /**
         * @description * `Polygon` - Polygon
         * @enum {string}
         */
        PolygonTypeEnum: "Polygon";
        /** @description RFC 7807 problem details; media type application/problem+json. */
        Problem: {
            /** @description A sentence a person can act on. */
            detail: string;
            status: number;
            /** @description Short classification, e.g. 'Invalid area'. */
            title: string;
            /** @description Always "about:blank". */
            type: string;
        };
        /** @description Where a KPI's band boundaries come from. */
        Source: {
            kind: components["schemas"]["SourceKind"];
            label: string;
            note?: string;
            /** Format: uri */
            url: string | null;
        };
        /**
         * @description * `citation` - CITATION
         *     * `derived` - DERIVED
         *     * `chosen` - CHOSEN
         * @enum {string}
         */
        SourceKind: "citation" | "derived" | "chosen";
        /**
         * @description * `ok` - ok
         * @enum {string}
         */
        StatusEnum: "ok";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type Area = components['schemas']['Area'];
export type AreaSource = components['schemas']['AreaSource'];
export type Band = components['schemas']['Band'];
export type BreakdownItem = components['schemas']['BreakdownItem'];
export type ContextItem = components['schemas']['ContextItem'];
export type Denominator = components['schemas']['Denominator'];
export type District = components['schemas']['District'];
export type Feature = components['schemas']['Feature'];
export type FeatureCollection = components['schemas']['FeatureCollection'];
export type FeatureCollectionTypeEnum = components['schemas']['FeatureCollectionTypeEnum'];
export type FeatureProperties = components['schemas']['FeatureProperties'];
export type FeatureTypeEnum = components['schemas']['FeatureTypeEnum'];
export type Health = components['schemas']['Health'];
export type Kpi = components['schemas']['Kpi'];
export type KpiRequestRequest = components['schemas']['KpiRequestRequest'];
export type KpiResponse = components['schemas']['KpiResponse'];
export type Layer = components['schemas']['Layer'];
export type Layers = components['schemas']['Layers'];
export type Legend = components['schemas']['Legend'];
export type LegendItem = components['schemas']['LegendItem'];
export type LegendTypeEnum = components['schemas']['LegendTypeEnum'];
export type Meta = components['schemas']['Meta'];
export type PolygonRequest = components['schemas']['PolygonRequest'];
export type PolygonTypeEnum = components['schemas']['PolygonTypeEnum'];
export type Problem = components['schemas']['Problem'];
export type Source = components['schemas']['Source'];
export type SourceKind = components['schemas']['SourceKind'];
export type StatusEnum = components['schemas']['StatusEnum'];
export type $defs = Record<string, never>;
export interface operations {
    districts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["District"][];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    kpis: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["KpiRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiResponse"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
