# Generated by Django 5.2.17 on 2026-09-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KpiDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Matches a KpiSpec in code.', max_length=64, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('definition', models.TextField(help_text='One or two sentences: what this measures.')),
                ('not_claim', models.TextField(help_text='What this number explicitly does not tell you. Rendered on the card.', verbose_name='does not claim')),
                ('bands', models.JSONField(help_text='Ordered list of {"label": str, "max": number | null}; a value falls into the first band whose max it does not exceed. The last band must have max = null.')),
                ('source_kind', models.CharField(choices=[('citation', 'citation'), ('derived', 'derived'), ('chosen', 'chosen')], max_length=16)),
                ('source_label', models.CharField(max_length=200)),
                ('source_url', models.URLField(blank=True, default='')),
                ('source_note', models.TextField(blank=True, default='')),
                ('breakdown_note', models.TextField(blank=True, default='', help_text='Set when the KPI deliberately has no breakdown.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KPI definition',
                'ordering': ['key'],
            },
        ),
    ]
